### ISSUE TITLE
Angular.js is going crazy on the website

### ISSUE THREAD

**Issue by codepreneur** [balderdashy/www.sailsjs.org#56]
When you go here: sailsjs.org/#!documentation/models

Website starts jumping to different routes non stop blocking/locking the whole browser.

![image](https://cloud.githubusercontent.com/assets/3421858/6169130/4c941184-b2c3-11e4-9b38-ef7e81571217.png)

Video/GIF below.

![image](http://g.recordit.co/EkhYacfXqI.gif)

http://recordit.co/EkhYacfXqI

This happens on Mac OS X Yosemite, Chrome 40.0.2214.111 (64-bit) and Latest Firefox and Safari (I didn't test any other browsers)

**Comment by sgress454** [comment]
Thanks @codepreneur , looking into this right now

**Comment by sgress454** [comment]
@codepreneur should be fixed, mind verifying on your end and closing if it looks good?

**Comment by codepreneur** [comment]
Website still doesnt work properly (though it doesnt block the browser anymore), clicking on side nav links for example:

![image](https://cloud.githubusercontent.com/assets/3421858/6172854/6c2e01d6-b2db-11e4-94f2-ab86b82aeee4.png)

**Comment by sgress454** [comment]
I'm not seeing the original problem anymore, I do see the side-nav link problem but only in the anatomy section.  You're still seeing the redirect loop issue when clicking on documentation?

**Comment by sgress454** [comment]
Ok, looks like there was still an issue when clicking certain broken links (esp. from Google).  The general redirect has been fixed, as well as the anatomy links.

**Comment by phishy** [comment]
I have a pull request open that should take care of this.

**Comment by sgress454** [comment]
@phishy Thanks a ton for taking a look--are you still seeing these issues on the site?

**Comment by phishy** [comment]
We should chat. I rewrote the way routing works in general in my pull request.

**Comment by robwormald** [comment]
It's definitely crying out for some ui-router love.

**Comment by phishy** [comment]
Yeah that's next. For now I refactored so you can enter with urls like sailsjs.org/#!documentation or sailsjs.org/documentation. I also cleaned up all the URLs on the site removing hashbangs. Clone it, it should work pretty good. RFC.

**Comment by phishy** [comment]
https://github.com/phishy/www.sailsjs.org

**Comment by sgress454** [comment]
We should definitely chat before you go through all that, as there's some internal debate over whether to keep this a single-page app at all.  People really seem to dig it, and it makes for great loading times on mobile, but keeping it Google-able is a real challenge that we've had trouble keeping up with.  cc: @mikermcneil

**Comment by phishy** [comment]
Well, I already went through it!

What about something like readthedocs.org? 
http://sublime-text-unofficial-documentation.readthedocs.org/en/latest/

**Comment by phishy** [comment]
Also, Angular seems to have a SPA and it's Google-able so it's definitely do-able. ;-) But indeed, it's not easy.

**Comment by phishy** [comment]
Currently if I google "sails models" it returns a result. The problem is that when I click on that result it doesn't work, because it redirects. With the refactor I just did, it will.

**Comment by sgress454** [comment]
The bigger issue is that the link from Google for "sails models" goes to a page (sailsjs.org/#!documentation/models) that doesn't exist on the site anymore; Google is using old content to build its links.  The new page would be http://sailsjs.org/#!/documentation/concepts/ORM.  There are definitely ways to keep this updated, and we're using one, but it's cumbersome.

**Comment by phishy** [comment]
You can submit an updated sitemap with Google Webmaster tools. Let me know when you get a chance to take a look at the PR. I'd be sad to hear I just spent 6 hours last night for nothing.

**Comment by sgress454** [comment]
No no!  It is 100% appreciated, I just didn't want you to do a whole ui-router rewrite without talking it over first (that's what I was referring to).

**Comment by phishy** [comment]
Oh indeed. A ui-router rewrite would take a couple hours. No big thing, and actually no benefit as we're not currently using nested states.

**Comment by codepreneur** [comment]
Guys, just switch to Ember :P

**Comment by robwormald** [comment]
We should be nesting them tho. Shits pretty hairy right now.

**Comment by phishy** [comment]
We used Ember when I was working at Apple. I could not have disliked it
more. ;-)

**Comment by phishy** [comment]
@robwormald It's not so bad. I feel like I made a great step toward cleaning it up. I guess I'm waiting to hear back from Balderdash before moving forward any more..

**Comment by robwormald** [comment]
At last glance, Apple was using Angular anyway :-D

**Comment by phishy** [comment]
@robwormald Depends on the group.

**Comment by sgress454** [comment]
Thanks for your patience guys--a couple of us are traveling this week but we'll sort this out this over the next few days.

**Comment by phishy** [comment]
ping

**Comment by sgress454** [comment]
#58 merged, thanks again @phishy!

**Comment by phishy** [comment]
@sgress454 I take it you were able to test it locally? It seems your are fine with the approach then? I removed all of the URLs with hashbang, and added some rewrites in the routes. This should clean up all of the URLs throughout the site. The next point of concern is SEO, and page rendering in general for clients like Facebook, Tumblr, Google+ etc.

**Comment by phishy** [comment]
@sgress454 Is there a commit hook to autodeploy? I'd like to take a look at the final product to ensure that it is working how I expect in production.

**Comment by sgress454** [comment]
Yes, it works great locally.  Removing all of the hashbang URLs in the menus is fine; the static content we send to Google doesn't include the side menu anyway.  Currently we're using [Brombone](http://www.brombone.com/) to proxy that static content when we [get requests from Google](https://github.com/balderdashy/www.sailsjs.org/blob/master/api/hooks/SEOHook.js), but the content (and I think our sitemap) is out of date.  What I'd really like is a solution that just serves up the static content directly from the `.tmp/public` folder instead of proxying to Brombone, so we have more control over the SEO situation. 

It's deploying now, should be up in a minute.

**Comment by sgress454** [comment]
Had some problems deploying...rolled back and am looking into the issue.

**Comment by sgress454** [comment]
@phishy Ok--it's live now.  Turns out you need to use the AMD syntax when defining modules or else the minifying process kills the files (you can test it by running the site locally in production mode with `sails lift --prod).

**Comment by sgress454** [comment]
@phishy Alas, I'm seeing some issues with links inside the content, which are all hashbang links (see http://sailsjs.org/documentation/concepts/extending-sails/Hooks).  I think we need these to remain hashbangs for Google to crawl them, but they're not working with the new scheme...

**Comment by phishy** [comment]
Ultimately, you don't want hashbangs at all. So the content would need to be updated to reflect that. Then you can instruct google to crawl it with a meta tag. I'm definitely interested in talking about static solutions as well. Perhaps http://sailsjs-documentation.readthedocs.org/en/latest/
